name: backend-check-trivy-image
description: 'backend-check-trivy-image'
inputs:
  docker-username:
    description: docker-username
    required: true
  github-sha:
    description: github-sha
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: target
    - name: build image
      shell: bash
      run: |
        docker build -t ${{ inputs.docker-username }}/weather-api:sha-${{ inputs.github-sha }} .
    - name: trivy image scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: '${{ inputs.docker-username }}/weather-api:sha-${{ inputs.github-sha }}'
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        ignore-unfixed: true
    - name: upload trivy image scan results to GitHub security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-image-results.sarif'
        category: 'image'