name: frontend-e2e
description: 'frontend-e2e'
inputs:
  frontend-directory:
    description: Frontend directory from project root
    required: true
  node:
    description: Node version
    required: true
runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.frontend-directory }}/package-lock.json

    - name: npm ci
      working-directory: ${{ inputs.frontend-directory }}
      run: npm ci
      shell: bash

    - name: Cache Playwright Browsers
      working-directory: ${{ inputs.frontend-directory }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json', 'yarn.lock', 'pnpm-lock.yaml') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-

    - name: Install Playwright Browsers
      working-directory: ${{ inputs.frontend-directory }}
      run: npx playwright install --with-deps
      shell: bash

    - name: Start wiremock backend api
      working-directory: ${{ inputs.frontend-directory }}
      run: docker compose up -d
      shell: bash

    - name: Run Playwright tests
      working-directory: ${{ inputs.frontend-directory }}
      run: npm run e2e
      shell: bash

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ${{ inputs.frontend-directory }}/playwright-report/
        retention-days: 30