version: '3.6'

services:
  database:
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/1_database.sql:/docker-entrypoint-initdb.d/1_database.sql
      - ./src/main/resources/db/2_schema.sql:/docker-entrypoint-initdb.d/2_schema.sql
      - ./src/main/resources/db/3_data.sql:/docker-entrypoint-initdb.d/3_data.sql
    environment:
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: password1
  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "9000:8080"
    volumes:
      - ./src/main/resources/mappings:/home/wiremock/mappings
