version: '3.6'

services:
  app:
    image: oskarwestmeijer/weather-api:1.0.7
    container_name: app
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENWEATHERAPI_URLPATH=${OPENWEATHERAPI_URLPATH}
networks:
  default:
    name: homepage-proxy
    external: true