version: '3.6'

services:
  app:
    image: oskarwestmeijer/weather-api:1.0.8
    container_name: app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    expose:
      - "8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENWEATHERAPI_URLPATH=${OPENWEATHERAPI_URLPATH}
networks:
  default:
    name: homepage-proxy
    external: true