version: '3.6'

services:
  app:
    image: oskarwestmeijer/weather-api:1.0.9
    container_name: app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    expose:
      - "8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENWEATHERAPI_URLPATH=${OPENWEATHERAPI_URLPATH}
      - "SPRING_PROFILES_ACTIVE=prod"
  database:
    image: postgres:14.1
    container_name: database
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    expose:
      - "5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
networks:
  default:
    name: homepage-proxy
    external: true
volumes:
  data:
    name: homepage-data
    external: true