services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    deploy:
      resources:
        limits:
          memory: 500m
        reservations:
          memory: 500m
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus-prod.yml'
      - '--storage.tsdb.retention.time=6h'
      - '--storage.tsdb.retention.size=200MB'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:12.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 300m
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
networks:
  default:
    name: proxy
    external: true