version: '3.8'

services:
  weather-api:
    image: oskarwestmeijer/weather-api:latest
    container_name: weather-api
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
    expose:
      - "8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENWEATHERAPI_APPID=${OPENWEATHERAPI_APPID}
      - "SPRING_PROFILES_ACTIVE=prod"
  weather-ui:
    image: oskarwestmeijer/weather-ui:latest
    container_name: weather-ui
    deploy:
      resources:
        limits:
          memory: 100m
        reservations:
          memory: 100m
    expose:
      - "80"
    restart: always
    volumes:
      - ./frontend/weather-ui/nginx/conf.d/:/etc/nginx/conf.d/:ro
networks:
  default:
    name: proxy
    external: true
