services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    deploy:
      resources:
        limits:
          memory: 500m
        reservations:
          memory: 500m
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus-prod.yml'
      - '--web.external-url=https://prometheus.oskar-westmeijer.com'
      - '--storage.tsdb.retention.time=6h'
      - '--storage.tsdb.retention.size=200MB'
    volumes:
      - ./prometheus-prod.yml:/etc/prometheus/prometheus-prod.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana-oss:12.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 300m
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://grafana.oskar-westmeijer.com
      - GF_SERVER_DOMAIN=grafana.oskar-westmeijer.com

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

networks:
  default:
    name: proxy
    external: true

volumes:
  prometheus_data: {}