version: '3.6'

services:
  weather-api:
    image: oskarwestmeijer/weather-api:latest
    container_name: weather-api
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    expose:
      - "8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENWEATHERAPI_APPID=${OPENWEATHERAPI_APPID}
      - "SPRING_PROFILES_ACTIVE=prod"
  weather-ui:
    image: oskarwestmeijer/weather-ui:1.7.7
    container_name: weather-ui
    deploy:
      resources:
        limits:
          memory: 250m
        reservations:
          memory: 250m
    expose:
      - "80"
    restart: always
networks:
  default:
    name: server-infrastructure-proxy
    external: true
