# obtained from secrets, referenced in docker-compose file
spring:
  config.activate.on-profile: prod
  datasource:
    url:
    username:
    password:
  liquibase:
    contexts: prod
openweatherapi:
  baseUrl: "https://api.openweathermap.org/data/2.5"
  appId:
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
