{
 "title": "weather-api",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus cleanup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_tsdb_compactions_total",
     "legendFormat": "compactions"
    },
    {
     "expr": "prometheus_tsdb_wal_truncations_total",
     "legendFormat": "wal_truncations"
    },
    {
     "expr": "prometheus_tsdb_head_chunks_removed_total",
     "legendFormat": "head_chunks_removed"
    }
   ]
  },
  {
   "title": "Prometheus storage sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "storage_blocks_size"
    },
    {
     "expr": "prometheus_tsdb_wal_storage_size_bytes",
     "legendFormat": "wal_size"
    },
    {
     "expr": "prometheus_tsdb_head_chunks_storage_size_bytes",
     "legendFormat": "head_chunks_size"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM memory used (details)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}