openapi: "3.0.3"
servers:
  - url: https://api.oskar-westmeijer.com
    description: url of production environment
info:
  description: |
    # Introduction
    Frontend specific Api to populate the charts.
  version: 1.0.0
  title: Weather-Api
externalDocs:
  description: https://github.com/OskarWestmeijer/weather-api
  url: 'https://github.com/OskarWestmeijer/weather-api'

paths:
  /chart/locations:
    get:
      summary: Get all locations enriched with current weather data
      operationId: getChartLocations
      tags:
        - chart_locations_resource
      responses:
        '200':
          description: Get all locations enriched with current weather data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChartLocationsResponse"
components:
  schemas:
    ChartLocationDto:
      type: object
      description: Requestable location
      required:
        - locationId
        - cityName
        - countryCode
        - temperature
        - humidity
        - windSpeed
        - recordedAt
      properties:
        locationId:
          type: integer
          format: int32
          description: api locationId, request weather with this id
          example: 1
        cityName:
          type: string
          description: city name in countries local spelling
          example: "Hamburg"
        countryCode:
          type: string
          description: ISO 3166-1 ALPHA-3 codes
          example: "GER"
        temperature:
          type: number
          format: double
          example: "11.45"
        humidity:
          type: integer
          format: int32
          example: "55"
        windSpeed:
          type: number
          format: double
          example: "2.57"
        recordedAt:
          type: string
          format: date-time
          example: "2022-08-29T21:56:18.602546Z"

    ChartLocationsResponse:
      type: object
      description: Container for multiple chart location elements.
      required:
        - chart-locations
      properties:
        chart-locations:
          type: array
          items:
            $ref: "#/components/schemas/ChartLocationDto"
