name: frontend-build-and-test
description: 'frontend-build-and-test'
inputs:
  frontend-directory:
    description: Frontend directory from project root
    required: true
runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm test
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: npm test
    - name: npm ci
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: npm ci
    - name: npm run build
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: CI=false npm run build