name: frontend-build-and-test
description: 'frontend-build-and-test'
runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm ci
      shell: bash
      run: npm ci
    - name: npm run build
      shell: bash
      run: CI=false npm run build