name: frontend-build-and-test
description: "frontend-build-and-test"
inputs:
  frontend-directory:
    description: Frontend directory from project root
    required: true
  node:
    description: Node version
    required: true

runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: "npm"
        cache-dependency-path: ${{ inputs.frontend-directory }}/package-lock.json

    - name: npm ci
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: npm ci

    - name: npm test
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: npm run test-headless

    - name: npm run build
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: CI=true npm run build
